import React,{useEffect,useState} from 'react';
import {ArrowDown,ArrowRight,Check,MessageCircle,Play,ShieldCheck,Sparkles,Users,Video} from 'lucide-react';

const A='/surya-portfolio/comski/';
const screens={home:A+'home.webp',practice:A+'practice.webp',feedback:A+'feedback.webp',journey:A+'journey.webp',record:A+'record.webp'};

function SectionLabel({num,label}:{num:string;label:string}){return <div className="cs-label"><span>{num}</span><b>{label}</b></div>}
function Reveal({children,delay=0}:{children:React.ReactNode;delay?:number}){const[on,setOn]=useState(false);useEffect(()=>{const els=document.querySelectorAll('.cs-reveal');const io=new IntersectionObserver(e=>e.forEach(x=>{if(x.isIntersecting)x.target.classList.add('is-visible')}),{threshold:.12});els.forEach(x=>io.observe(x));return()=>io.disconnect()},[]);return <div className="cs-reveal" style={{transitionDelay:delay+'s'}}>{children}</div>}
function Screen({src,label,alt}:{src:string;label:string;alt:string}){return <figure className="cs-screen"><div className="cs-browser"><i/><i/><i/><small>{label}</small></div><img src={src} alt={alt} loading="lazy" onError={(e)=>{(e.currentTarget.parentElement as HTMLElement).classList.add('asset-missing');e.currentTarget.style.display='none'}}/><div className="cs-screen-fallback"><b>{label}</b><span>Connect the exported Figma screen at <code>{src}</code></span></div></figure>}
export default function ComskiCaseStudy(){
 const [progress,setProgress]=useState(0);
 useEffect(()=>{const fn=()=>{const h=document.documentElement.scrollHeight-innerHeight;setProgress(h?scrollY/h:0)};addEventListener('scroll',fn,{passive:true});fn();return()=>removeEventListener('scroll',fn)},[]);
 return <main className="comski-case" id="top">
  <div className="cs-progress"><span style={{transform:'scaleX('+progress+')'}}/></div>
  <nav className="cs-nav"><a href="/surya-portfolio/"><b>Surya Kiran</b><span>ComSki / Case Study</span></a><a href="/surya-portfolio/">Back to portfolio ↗</a></nav>

  <header className="cs-hero">
   <div className="cs-hero-bg"/>
   <div className="cs-hero-inner">
    <div className="cs-kicker"><span>02 / 04</span><span>AI · EDTECH · PRODUCT DESIGN</span></div>
    <div className="cs-hero-copy"><p>COMSKI</p><h1>One AI coach.<br/><em>Two very different learners.</em></h1><div className="cs-hero-grid"><p>Designing an adaptive communication-learning system for students and professionals without fragmenting the core product experience.</p><div className="cs-meta"><div><small>ROLE</small><b>Product Designer</b></div><div><small>PRODUCT</small><b>AI communication coach</b></div><div><small>PLATFORM</small><b>Web · video practice</b></div><div><small>TOOLS</small><b>Figma · prototyping</b></div></div></div></div>
    <a className="cs-scroll" href="#s01"><span>EXPLORE THE CASE STUDY</span><ArrowDown size={15}/></a>
   </div>
   <div className="cs-hero-visual"><div className="cs-hero-orbit o1"/><div className="cs-hero-orbit o2"/><div className="cs-hero-dashboard"><div className="fake-side"><b>ComSki</b><span>Home</span><span>Practice</span><span>My Journey</span><span>Feedback</span></div><div className="fake-main"><small>GOOD MORNING</small><h3>Continue your journey</h3><div className="fake-cards"><div><b>Google SDE Journey</b><i/></div><div><strong>+20%</strong><small>Confidence</small></div><div><strong>+15%</strong><small>Body Language</small></div></div><div className="fake-bottom"><div><Play size={13}/> Practice in real scenarios</div><div><Sparkles size={13}/> AI Feedback</div></div></div></div><div className="cs-hero-phone"><div className="phone-head"><span>● 00:45</span><b>Video Practice</b></div><div className="phone-person">◒</div><div className="phone-wave">▂▅▇▃▆▂▅</div></div><div className="cs-chip chip-one">Student <small>Build confidence</small></div><div className="cs-chip chip-two">Professional <small>Interview readiness</small></div></div>
  </header>

  <section className="cs-intro"><div><span>THE PRODUCT</span><h2>A communication coach that adapts the <em>practice context</em> without splitting the experience.</h2></div><p>ComSki combines scenario-based practice, recording and AI feedback. The design challenge was to make the same system useful for learners preparing for academic situations and professionals preparing for real opportunities.</p></section>

  <article className="cs-layout">
   <aside className="cs-chapters"><a href="#s01">01 <b>PROBLEM</b></a><a href="#s02">02 <b>RESEARCH</b></a><a href="#s03">03 <b>INSIGHT</b></a><a href="#s04">04 <b>SYSTEM</b></a><a href="#s05">05 <b>DECISIONS</b></a><a href="#s06">06 <b>OUTCOME</b></a></aside>

   <div className="cs-content">
    <section id="s01" className="cs-section"><SectionLabel num="01" label="THE PROBLEM"/><h2>One product had to support <em>two different reasons to improve.</em></h2><div className="cs-two"><p>Students needed confidence for presentations and everyday communication. Professionals needed practice that felt closer to interviews, meetings and real workplace situations.</p><p>The risk was creating two disconnected experiences. The product needed shared primitives — practice, recording, feedback and progress — while letting the scenario context change.</p></div><div className="cs-principle"><b>DESIGN PROBLEM</b><strong>How might ComSki adapt the <em>context</em> of coaching without changing the underlying mental model?</strong></div></section>

    <section id="s02" className="cs-section"><SectionLabel num="02" label="RESEARCH & VALIDATION"/><h2>The key question was not “what can AI detect?”<br/><em>It was “what will a learner act on?”</em></h2><div className="cs-research-grid"><article><Users/><span>USER CONTEXT</span><h3>Different scenarios, shared needs</h3><p>Across academic and professional practice, the recurring needs were preparation, a low-pressure place to rehearse, visible progress and actionable feedback.</p></article><article><Video/><span>PRACTICE LOOP</span><h3>Practice had to feel safe enough to repeat</h3><p>The recording experience was treated as rehearsal rather than performance. The interface keeps the learner focused on the scenario before surfacing detailed analysis.</p></article><article><MessageCircle/><span>FEEDBACK</span><h3>Feedback must become a next action</h3><p>Signals such as confidence, body language and speech clarity were grouped into understandable coaching cues instead of presenting raw analysis.</p></article></div><div className="cs-validation"><span>WHAT WAS TESTED</span><div><b>Scenario comprehension</b><small>Could a learner tell what they were practicing and why?</small></div><div><b>Freeze / avoidance moments</b><small>Did the flow reduce hesitation between choosing a practice task and starting?</small></div><div><b>Feedback usefulness</b><small>Could a learner identify one concrete change to try next?</small></div></div><p className="cs-research-note">The case study uses the research/validation details available from the project work. Exact participant counts and study protocol are intentionally not fabricated here where the source material did not establish them.</p></section>

    <section id="s03" className="cs-section"><SectionLabel num="03" label="THE INSIGHT"/><div className="cs-insight"><span>THE DESIGN INSIGHT</span><h2>When learners hesitate, the problem is often <em>context switching</em> — not lack of motivation.</h2><p>ComSki therefore keeps the interaction model stable while changing scenario framing, practice prompts and feedback emphasis. A learner should not have to relearn the product because the goal changed from “present better” to “interview better.”</p></div><div className="cs-flow"><div><small>01</small><b>Choose context</b><span>Academic or professional</span></div><i>→</i><div><small>02</small><b>Practice</b><span>Speak in a realistic scenario</span></div><i>→</i><div><small>03</small><b>Record</b><span>Capture the attempt</span></div><i>→</i><div className="active"><small>04</small><b>AI feedback</b><span>Turn signals into coaching</span></div><i>→</i><div><small>05</small><b>Repeat</b><span>Apply the feedback</span></div></div></section>

    <section id="s04" className="cs-section"><SectionLabel num="04" label="THE SYSTEM"/><h2>One core model.<br/><em>Multiple learning contexts.</em></h2><div className="cs-system"><div className="system-card"><small>SHARED CORE</small><h3>Practice → Record → Feedback → Progress</h3><p>The same loop anchors every scenario so familiarity compounds over time.</p></div><div className="system-column"><div><b>STUDENT</b><span>School presentations · confidence · communication basics</span></div><div><b>PROFESSIONAL</b><span>Interviews · workplace communication · opportunity readiness</span></div><div><b>AI LAYER</b><span>Content structure · confidence · body language · speech clarity</span></div></div></div></section>

    <section id="s05" className="cs-section cs-decisions"><SectionLabel num="05" label="SCREEN DECISIONS"/><h2>The interface is designed around <em>what the learner needs next.</em></h2><div className="cs-decision"><div><span>01 / ORIENTATION</span><h3>Put the learner's context before the metrics.</h3><p>The home surface leads with the active journey and practice opportunities, while confidence and body-language signals remain secondary. This keeps the first read actionable.</p></div><Screen src={screens.home} label="home / journey" alt="ComSki home and journey screen"/></div><div className="cs-decision reverse"><Screen src={screens.practice} label="practice" alt="ComSki practice screen"/><div><span>02 / PRACTICE</span><h3>Make realistic practice easier to start.</h3><p>Scenario framing reduces the blank-page feeling. The learner knows what situation they are preparing for before the camera or recording state takes over.</p></div></div><div className="cs-decision"><div><span>03 / FEEDBACK</span><h3>Convert analysis into coaching cues.</h3><p>Instead of exposing a dense AI report, the hierarchy moves from a headline signal to a small number of understandable improvements.</p></div><Screen src={screens.feedback} label="AI feedback" alt="ComSki AI feedback screen"/></div><div className="cs-decision reverse"><Screen src={screens.record} label="recording" alt="ComSki recording screen"/><div><span>04 / RECORDING</span><h3>Make rehearsal feel lighter than evaluation.</h3><p>The recording state is visually focused and time-bounded so the learner can concentrate on speaking rather than interpreting the interface.</p></div></div></section>

    <section id="s06" className="cs-section"><SectionLabel num="06" label="OUTCOME & LEARNINGS"/><h2>The design outcome was a <em>repeatable coaching loop</em>, not another dashboard.</h2><div className="cs-outcome-grid"><article><ShieldCheck/><b>TRUST</b><h3>AI stays explainable at the point of action.</h3><p>Feedback is connected to the practice attempt, making the system feel like a coach rather than a scoring engine.</p></article><article><Sparkles/><b>ADAPTABILITY</b><h3>Contexts change; the core interaction model does not.</h3><p>Student and professional journeys share the same product grammar while the scenario content changes.</p></article><article><Check/><b>MEASURE NEXT</b><h3>Optimise for repeated practice and action.</h3><p>The next validation layer should measure practice starts, completion, repeat sessions and whether learners act on specific feedback.</p></article></div><div className="cs-reflection"><span>DESIGN REFLECTION</span><p>ComSki taught me to treat AI feedback as part of an interaction loop, not as a feature that can be dropped into a screen. The strongest interface was the one that made the next attempt feel obvious.</p></div></section>
   </div>
  </article>
  <footer className="cs-footer"><span>COMSKI / CASE STUDY</span><h2>Designing the space between <em>practice and confidence.</em></h2><a href="/surya-portfolio/">Back to portfolio <ArrowRight size={17}/></a></footer>
 </main>
}