import React from 'react';
import { motion } from 'framer-motion';
import { ArrowDown, ArrowRight, Check, ChevronRight, FileText, UploadCloud, Sparkles, ShieldCheck } from 'lucide-react';
import './genesis-style2.css';

const chapters = [
  ['01','Context','Why Genesis'],['02','Problem','Where testing breaks down'],['03','Approach','A guided AI workflow'],['04','Project setup','Start with context'],['05','Artifacts','Give AI the right inputs'],['06','Test data','Prepare the environment'],['07','AI configuration','Make intelligence visible'],['08','Review','Keep humans in control'],['09','Outcome','From setup to insight']
] as const;

function MockScreen({ kind }: { kind: string }) {
  const title = kind === 'project' ? 'Project Details' : kind === 'artifacts' ? 'Input Artifacts' : kind === 'data' ? 'Test Data Setup' : kind === 'ai' ? 'AI Configuration' : kind === 'review' ? 'Review & Validate' : 'Genesis Dashboard';
  return <div className="s2-screen"><div className="s2-windowbar"><i/><i/><i/><span>{title}</span></div><div className="s2-app"><aside><b>G</b><em/><em/><em/><em/></aside><div className="s2-screenbody"><small>GENESIS / {title.toUpperCase()}</small><h3>{kind === 'dashboard' ? 'See what needs attention.' : `Build your ${kind === 'ai' ? 'AI workflow' : 'testing workspace'}.`}</h3>{kind === 'project' && <><label>PROJECT NAME<div>Project Genesis</div></label><label>DESCRIPTION<div>AI-assisted testing workspace</div></label></>}{kind === 'artifacts' && <div className="s2-cards"><article><FileText/><b>User Stories</b><span>Requirements & acceptance criteria</span></article><article><UploadCloud/><b>API Contracts</b><span>OpenAPI / Swagger</span></article><article><UploadCloud/><b>GitHub Repository</b><span>Source code context</span></article></div>}{kind === 'data' && <div className="s2-form"><p>Database connection <strong>Configured</strong></p><p>Enable synthetic test data <i className="toggle"/></p></div>}{kind === 'ai' && <div className="s2-form"><p>Programming language <strong>TypeScript ›</strong></p><p>LLM model <strong>GPT model ›</strong></p><p>Capabilities <strong>✓ Test generation · ✓ Analysis</strong></p></div>}{kind === 'review' && <div className="s2-summary"><p>Language <b>TypeScript</b></p><p>LLM Model <b>GPT model</b></p><p>Synthetic data <b>Enabled</b></p><button>Create Project <ArrowRight size={13}/></button></div>}{kind === 'dashboard' && <div className="s2-dashboard"><div><b>12</b><span>Active projects</span></div><div><b>47</b><span>Test cycles</span></div><div><b>94.2%</b><span>Pass rate</span></div><div><b>87.5%</b><span>Coverage</span></div><svg viewBox="0 0 500 120"><path d="M0 95 C50 80 65 105 110 70 S180 90 220 55 S290 72 335 40 S420 58 500 18"/></svg></div>}</div></div></div>;
}

function Chapter({ number, label, title, body, screen, reverse=false }: {number:string;label:string;title:string;body:string;screen?:string;reverse?:boolean}) { return <section className={`s2-chapter ${reverse?'reverse':''}`} id={`s2-${number}`}><div className="s2-copy"><span className="s2-number">{number}</span><small>{label}</small><h2>{title}</h2><p>{body}</p><a href="#s2-next">Continue <ArrowDown size={14}/></a></div>{screen && <motion.div className="s2-visual" initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.7}}><MockScreen kind={screen}/></motion.div>}</section> }

export default function GenesisStyle2(){ return <main className="genesis-s2">
  <nav className="s2-top"><span>GENESIS / CASE STUDY</span><a href="../../">Back to portfolio</a></nav>
  <header className="s2-hero"><div><p>PRODUCT DESIGN · AI · SAAS</p><h1>Making AI-powered testing feel <em>guided.</em></h1><p className="hero-lead">Genesis is a test automation platform designed to help QA teams move from product context to test artifacts with less manual setup — while keeping people in control.</p><div className="s2-meta"><span><b>ROLE</b> Product Designer · Sole designer</span><span><b>TEAM</b> PM · Engineers · Stakeholders</span><span><b>TIMELINE</b> ~6 months</span></div></div><div className="hero-visual"><MockScreen kind="dashboard"/></div><span className="scroll">SCROLL TO EXPLORE <ArrowDown size={15}/></span></header>
  <aside className="s2-index">{chapters.map(([n,l])=><a key={n} href={`#s2-${n}`}>{n}<span>{l}</span></a>)}</aside>
  <section className="s2-intro" id="s2-01"><div><span>01 / CONTEXT</span><h2>A testing product had to explain both the workflow <em>and the intelligence inside it.</em></h2></div><p>My focus was not simply making the screens look polished. I shaped the experience around a technical user's need to understand what to provide, what Genesis will do with it, and when they can review the result.</p></section>
  <Chapter number="02" label="THE PROBLEM" title="The complexity was real. The interface didn't need to expose all of it at once." body="Project information, requirements, APIs, test data, AI settings and validation all belong to the same setup journey. The design opportunity was to turn those dependencies into a sequence people can understand." screen="project" />
  <section className="s2-statement" id="s2-03"><span>03 / DESIGN APPROACH</span><h2>One complex workflow.<br/><em>Five understandable decisions.</em></h2><div className="s2-flow">{['Project details','Input artifacts','Test data','AI configuration','Review & validate'].map((x,i)=><motion.div key={x} whileHover={{y:-6}}><b>0{i+1}</b><span>{x}</span>{i<4&&<ChevronRight/>}</motion.div>)}</div></section>
  <Chapter number="04" label="PROJECT SETUP" title="Start with context before configuration." body="The first step establishes what is being tested. That simple framing keeps the user oriented before technical choices begin." screen="project" reverse />
  <Chapter number="05" label="INPUT ARTIFACTS" title="Show the AI what it can work from." body="User stories, API contracts and a GitHub repository become explicit inputs. This makes the source of AI-generated test work visible rather than mysterious." screen="artifacts" />
  <Chapter number="06" label="TEST DATA" title="Prepare the conditions behind the scenarios." body="Test data setup gives teams a clear place to connect supporting data and decide whether synthetic data should be enabled." screen="data" reverse />
  <Chapter number="07" label="AI CONFIGURATION" title="AI should be configurable, not magical." body="Language, model and capabilities are separated into visible choices. Users can understand what Genesis is about to use before it starts generating work." screen="ai" />
  <Chapter number="08" label="REVIEW & VALIDATE" title="The final screen is a confidence checkpoint." body="A consolidated review brings decisions back together. The user gets one last opportunity to verify the setup before creating the project." screen="review" reverse />
  <section className="s2-outcome" id="s2-09"><div><span>09 / OUTCOME</span><h2>From setup to insight.</h2><p>The workflow continues after project creation. Dashboard and reporting surfaces help teams understand test activity, coverage, pass rate and areas that need attention.</p></div><MockScreen kind="dashboard"/></section>
  <section className="s2-lessons"><span>DESIGN PRINCIPLES</span><div><h3>Progressive disclosure</h3><p>Reveal complexity only when the user needs it.</p></div><div><h3>Visible AI</h3><p>Make important model and capability choices explicit.</p></div><div><h3>Human control</h3><p>Give users a clear review point before AI work proceeds.</p></div><div><h3>Explain the screen</h3><p>Every important state should tell users what is happening and what to do next.</p></div></section>
  <footer className="s2-footer"><span>GENESIS / END</span><h2>A product case study built around the decisions behind the screens.</h2><a href="../../">Return to portfolio <ArrowRight size={16}/></a></footer>
</main> }
