import React from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, Check, Eye, GitBranch, Layers3, ShieldCheck, SlidersHorizontal, Sparkles, Users } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import GenesisHero from './GenesisHero';
import './genesis-case-study.css';
import './genesis-original-screens.css';
import './genesis-v5.css';

const screens = {
  context: '/surya-portfolio/genesis/Project-Details.webp', inputs: '/surya-portfolio/genesis/Input-Artifacts.webp', data: '/surya-portfolio/genesis/Test-Data-Setup.webp', ai: '/surya-portfolio/genesis/AI-Configuration.webp', review: '/surya-portfolio/genesis/Review-Validate.webp', dashboard: '/surya-portfolio/genesis/Dashboard.webp', reports: '/surya-portfolio/genesis/Reports.webp',
};

function Reveal({ children, delay = 0, className = '' }) { return <motion.div className={className} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .65, delay, ease: [.22, 1, .36, 1] }}>{children}</motion.div>; }
function Section({ number, eyebrow, title, copy, children, className = '' }) { return <section className={`v5-section ${className}`}><div className="v5-heading"><div className="v5-index"><span>{number}</span><i /></div><div><p className="v5-kicker">{eyebrow}</p><h2>{title}</h2>{copy && <p className="v5-copy">{copy}</p>}</div></div>{children}</section>; }
function Screen({ src, alt, label }) { return <div className="v5-screen"><div className="v5-screen-top"><span /><span /><span /><small>{label}</small></div><img src={src} alt={alt} loading="lazy" decoding="async" width="1920" /></div>; }

function Context() { return <section className="v5-context"><div className="v5-context-lead"><p className="v5-kicker">THE PRODUCT</p><h2>Genesis was an exercise in designing an AI-assisted testing system, not another test-generation screen.</h2><p>I designed the end-to-end product experience around test context, artifact ingestion, AI configuration, validation, execution visibility and reporting — translating a technically complex workflow into a coherent interaction model.</p></div><div className="v5-meta"><div><span>ROLE</span><strong>Product Designer<br />End-to-end ownership</strong></div><div><span>TEAM</span><strong>PM · Engineering<br />Technical stakeholders</strong></div><div><span>PRODUCT</span><strong>AI test automation<br />B2B SaaS platform</strong></div><div><span>DESIGN SCOPE</span><strong>Workflow architecture<br />UI · Interaction · Systems</strong></div></div></section>; }

function SystemModel() { const steps: Array<[string, string, string, LucideIcon]> = [['01', 'Context', 'Project + requirements', Layers3], ['02', 'Artifacts', 'Inputs + test data', GitBranch], ['03', 'Configure', 'AI behaviour', SlidersHorizontal], ['04', 'Validate', 'Human-in-the-loop', ShieldCheck], ['05', 'Observe', 'Execution + reporting', Eye]]; return <><div className="v5-system"><div className="v5-system-line" />{steps.map(([n, title, sub, Icon]) => <motion.article key={n} whileHover={{ y: -7 }} className="v5-system-node"><span>{n}</span><div><Icon size={18} /></div><h3>{title}</h3><p>{sub}</p></motion.article>)}</div><div className="v5-state-model"><div className="v5-state-copy"><span>WORKFLOW STATE</span><h3>Every stage carries context forward.</h3><p>The experience is structured so users can understand what the system knows, what it is doing, and what requires their input before the next state begins.</p></div><div className="v5-state-track"><div><b>INPUT</b><span>Context + artifacts</span></div><i>→</i><div><b>PROCESS</b><span>AI generation</span></div><i>→</i><div className="active"><b>CONTROL</b><span>Review + validate</span></div><i>→</i><div><b>OUTPUT</b><span>Execution + reports</span></div></div></div></>; }
function Tension({ icon: Icon, number, title, copy, detail }) { return <article className="v5-tension"><div className="v5-tension-top"><span>{number}</span><Icon size={18} /></div><h3>{title}</h3><p>{copy}</p><div className="v5-tension-detail"><b>DESIGN RESPONSE</b><span>{detail}</span></div></article>; }
function Decision({ number, eyebrow, title, copy, src, alt, label, reverse = false, children }) { return <section className={`v5-decision ${reverse ? 'reverse' : ''}`}><div className="v5-decision-copy"><span className="v5-decision-number">{number}</span><p className="v5-kicker">{eyebrow}</p><h2>{title}</h2><p>{copy}</p>{children}</div><Reveal className="v5-decision-visual"><Screen src={src} alt={alt} label={label} /></Reveal></section>; }
function Tradeoffs() { return <div className="v5-tradeoffs"><div className="v5-tradeoff"><span>01</span><div><b>Automation ↔ accountability</b><p>As automation increases, system inputs, generated output and user intervention points need to remain traceable.</p></div></div><div className="v5-tradeoff"><span>02</span><div><b>Configurability ↔ cognitive load</b><p>Technical controls should expose meaningful system behaviour without turning configuration into an engineering task.</p></div></div><div className="v5-tradeoff"><span>03</span><div><b>System complexity ↔ information hierarchy</b><p>Genesis spans multiple workflow states, so each surface needs a clear responsibility within the broader architecture.</p></div></div></div>; }

export default function GenesisV5() { return <main className="genesis-case-study genesis-v5"><GenesisHero /><Context />
<Section number="01" eyebrow="PROBLEM SPACE" title="The product challenge was orchestration, not test generation." copy="Generating test cases is only one stage of an automation workflow. Users still need to establish project context, provide source artifacts and data, configure system behaviour, review generated output, execute tests and interpret coverage and results."><Reveal><div className="v5-problem"><div className="v5-problem-old"><span>LEGACY WORKFLOW</span><h3>Testing context is fragmented across requirements, code, test data, configuration and execution tooling.</h3><div className="v5-chip-row"><b>Requirements</b><b>API / code</b><b>Test data</b><b>Configuration</b><b>Execution</b><b>Reports</b></div></div><div className="v5-problem-arrow"><ArrowRight size={19} /></div><div className="v5-problem-new"><span>PRODUCT OPPORTUNITY</span><h3>Model the testing lifecycle as one contextual, guided system.</h3><div className="v5-flow"><b>Context</b><i>→</i><b>AI</b><i>→</i><b>Validate</b><i>→</i><b>Observe</b></div></div></div></Reveal></Section>
<Section number="02" eyebrow="DESIGN THESIS" title="Increase automation without turning the system into a black box." copy="The core UX question was where AI should accelerate execution and where the product should expose state, inputs and decision points. The resulting principle was simple: automate the repetitive path, preserve human control over consequential states."><Reveal><div className="v5-question"><div><Sparkles size={21} /><span>AI LAYER</span><h3>Accelerate repetitive test-authoring and configuration work.</h3></div><div><Users size={21} /><span>HUMAN LAYER</span><h3>Review and own decisions that affect test validity.</h3></div><div><ShieldCheck size={21} /><span>UX LAYER</span><h3>Make system state, provenance and intervention points legible.</h3></div></div></Reveal></Section>
<Section number="03" eyebrow="SYSTEM ARCHITECTURE" title="I designed around the workflow state, not the individual screen." copy="The interface model starts with the information Genesis needs to operate and follows that context through configuration, validation and execution. This gave the product a consistent mental model across setup and operational surfaces."><Reveal><SystemModel /></Reveal></Section>
<Section number="04" eyebrow="PRODUCT TENSIONS" title="Three constraints shaped the interaction model." copy="The design decisions were driven by the relationship between automation, technical configurability and information density — the recurring tensions in an AI-powered B2B workflow."><div className="v5-tension-grid"><Tension number="01" icon={ShieldCheck} title="Automation without opaque behaviour" copy="AI-generated work is easier to trust when users can inspect the context that informed it and understand where they can intervene." detail="Expose inputs, preserve provenance and introduce a deliberate validation state." /><Tension number="02" icon={SlidersHorizontal} title="Technical control without configuration overload" copy="Model and generation controls need to communicate system behaviour without requiring users to reason about implementation details." detail="Group controls by user intent and expose complexity progressively." /><Tension number="03" icon={Eye} title="Operational depth without dashboard noise" copy="Execution, coverage and reporting create dense information environments where hierarchy matters more than decoration." detail="Separate overview, status and diagnostic depth through progressive disclosure." /></div></Section>
<Decision number="05" eyebrow="DECISION 01 · ARTIFACT CONTEXT" title="Expose the inputs that establish AI execution context." copy="I treated source artifacts as first-class objects in the workflow rather than hidden dependencies. Requirements, API definitions and source-code context establish the basis for downstream generation, so the interface makes that context visible before the system produces test output." src={screens.inputs} alt="Genesis Input Artifacts screen" label="input artifacts" reverse><div className="v5-note"><Check size={15} /><span>Design principle: make system inputs inspectable before users evaluate system output.</span></div></Decision>
<Decision number="06" eyebrow="DECISION 02 · AI CONFIGURATION" title="Turn model behaviour into an explicit product surface." copy="AI configuration exposes the parameters that materially affect generation rather than hiding them behind a single action. The interface creates a controlled boundary between model capability and user intent, making configuration understandable without exposing unnecessary implementation detail." src={screens.ai} alt="Genesis AI Configuration screen" label="ai configuration"><div className="v5-note"><Check size={15} /><span>Design principle: expose meaningful AI controls at the level of user intent, not model internals.</span></div></Decision>
<Decision number="07" eyebrow="DECISION 03 · HUMAN-IN-THE-LOOP" title="Make validation a defined workflow state, not an afterthought." copy="Review & Validate acts as a control point between AI-assisted generation and downstream execution. Bringing project context and generated configuration together creates an explicit opportunity to inspect, correct and confirm before the workflow progresses." src={screens.review} alt="Genesis Review and Validate screen" label="review & validate" reverse><div className="v5-note"><Check size={15} /><span>Design principle: separate generation from execution with an intentional human validation state.</span></div></Decision>
<Section number="08" eyebrow="OBSERVABILITY & OPERATIONS" title="The workflow continues after generation." copy="An automation product needs more than a setup flow. Dashboard and reporting surfaces provide the operational layer for understanding execution state, test coverage and results after configuration is complete."><Reveal><div className="v5-results-grid"><Screen src={screens.dashboard} alt="Genesis Dashboard screen" label="dashboard" /><Screen src={screens.reports} alt="Genesis Reports screen" label="reports" /></div></Reveal></Section>
<Section number="09" eyebrow="DESIGN PRINCIPLES" title="What I would preserve as the system scales." copy="These principles are more durable than any individual UI treatment because they describe how the product should behave as AI capabilities and testing workflows evolve."><Reveal><Tradeoffs /></Reveal></Section>
<section className="v5-outcome"><div className="v5-outcome-inner"><p className="v5-kicker">PRODUCT OUTCOME</p><h2>Genesis shifts the interaction model from isolated test generation toward a contextual, inspectable and human-supervised automation workflow.</h2><div className="v5-outcome-points"><div><b>01</b><span>Context becomes an explicit input to AI-assisted generation.</span></div><div><b>02</b><span>AI configuration becomes visible and controllable rather than implicit.</span></div><div><b>03</b><span>Validation and operational reporting create clear human checkpoints across the lifecycle.</span></div></div></div></section>
<section className="v5-reflection"><div><p className="v5-kicker">DESIGN REFLECTION</p><h2>The central design problem was not how to make AI feel intelligent. It was how to define the boundary between system capability and human accountability.</h2><p>For complex AI products, the interface becomes part of the control system. Inputs, system state, generated output, configuration and validation need to be understandable as connected states — not presented as isolated screens. That became the foundation for the Genesis experience.</p></div></section>
<footer className="genesis-footer"><span>GENESIS / V5</span><h2>Designing AI-assisted testing as a transparent, configurable and human-supervised workflow.</h2><a href="../../">Back to portfolio <ArrowRight size={16} /></a></footer></main>; }
