import React from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, Check, ChevronRight, CircleDot, Eye, FileText, Layers3, ShieldCheck, SlidersHorizontal, Sparkles, UploadCloud } from 'lucide-react';
import GenesisHero from './GenesisHero';
import './genesis-case-study.css';
import './genesis-original-screens.css';

const setup = [
  { n:'01', title:'Project context', short:'Define the problem', text:'Start with what is being tested so the AI has a clear product context.', icon:Layers3 },
  { n:'02', title:'Input artifacts', short:'Bring the right context', text:'Give Genesis requirements, APIs and source-code context it can work from.', icon:UploadCloud },
  { n:'03', title:'Test data setup', short:'Prepare the conditions', text:'Connect the data and environments the generated scenarios depend on.', icon:SlidersHorizontal },
  { n:'04', title:'AI configuration', short:'Make AI explicit', text:'Choose the language, model and capabilities before generation begins.', icon:Sparkles },
  { n:'05', title:'Review & validate', short:'Keep humans in control', text:'Bring the important decisions together before the project is created.', icon:ShieldCheck },
];

const decisions = [
  ['Reduce repetitive effort','Use AI where teams repeatedly analyse, generate and organise testing work.'],
  ['Keep AI understandable','Make important AI inputs, model choices and capabilities visible.'],
  ['Keep humans accountable','Create deliberate review points before consequential work moves forward.'],
  ['Design the whole lifecycle','Connect setup, execution, monitoring and reporting into one product experience.'],
];

function Reveal({children,delay=0,className=''}){return <motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.65,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function SectionHeader({number,eyebrow,title,copy}){return <div className="genesis-section-heading"><div className="genesis-section-number"><span>{number}</span><i/></div><div><p className="genesis-section-kicker">{eyebrow}</p><h2>{title}</h2><p className="genesis-section-copy">{copy}</p></div></div>}
function ProjectSnapshot(){return <section className="genesis-snapshot"><div className="snapshot-intro"><p className="genesis-section-kicker">THE PROJECT, IN ONE MINUTE</p><h2>Genesis is an AI-powered test automation platform designed to reduce repetitive testing work while keeping the people responsible for quality in control.</h2><p>I shaped the end-to-end product experience as the sole designer — from product context and AI configuration to validation, monitoring and reporting.</p></div><div className="snapshot-facts"><div><span>ROLE</span><strong>Product Designer · Sole designer</strong></div><div><span>TEAM</span><strong>PM · Engineers · Stakeholders</strong></div><div><span>USERS</span><strong>QA · Test automation · QE · DevOps</strong></div><div><span>FOCUS</span><strong>AI-assisted testing · SaaS</strong></div></div></section>}
function BeforeAfter(){return <div className="genesis-before-after"><div className="story-column before"><div className="story-label"><span>THE TESTING CHALLENGE</span><b>01</b></div><h3>Testing takes more time than the test run itself.</h3><p>Teams spend effort understanding requirements, preparing data, creating test cases, configuring automation, investigating results and tracking coverage. Genesis was designed to reduce that surrounding manual work.</p><div className="fragment-stack"><span>Requirements</span><span>APIs & code</span><span>Test data</span><span>Test generation</span><span>Execution</span><span>Reporting</span></div></div><div className="story-arrow"><ArrowRight size={20}/></div><div className="story-column after"><div className="story-label"><span>THE PRODUCT OPPORTUNITY</span><b>02</b></div><h3>Let AI handle repetitive work while people retain the important decisions.</h3><p>The experience connects AI assistance with explicit human checkpoints, so speed does not come at the cost of visibility or control.</p><div className="sequence-mini"><span><b>AI</b>Analyze</span><span><b>AI</b>Generate</span><span><b>AI</b>Recommend</span><span><b>HUMAN</b>Review</span><span><b>HUMAN</b>Approve</span></div></div></div>}
function WorkflowMap(){return <div className="genesis-workflow-map"><div className="workflow-line"/>{setup.map(({n,title,text,icon:Icon})=><motion.article key={n} whileHover={{y:-7}} className="workflow-node"><span className="workflow-number">{n}</span><div className="workflow-icon"><Icon size={18}/></div><h3>{title}</h3><p>{text}</p></motion.article>)}</div>}
function OriginalScreen({src,alt,className=''}){return <div className={`genesis-original-screen ${className}`}><img src={src} alt={alt} loading="lazy"/></div>}
function Chapter({number,eyebrow,title,copy,visual,reverse=false}){return <section className={`genesis-case-section chapter-section ${reverse?'chapter-reverse':''}`}><div className="chapter-copy"><div className="chapter-number">{number}</div><p className="genesis-section-kicker">{eyebrow}</p><h2>{title}</h2><p>{copy}</p></div><Reveal className="chapter-visual">{visual}</Reveal></section>}
function States(){const states=[['Empty','Nothing to start yet','neutral'],['Input','Context received','active'],['Error','Something needs attention','error'],['Success','Action completed','success']];return <div className="genesis-state-strip">{states.map(([title,value,type])=><motion.div key={title} whileHover={{y:-5}} className={`state-card ${type}`}><small>{title}</small><div>{value}</div><span>{type==='error'?'!':type==='success'?'✓':'•'}</span></motion.div>)}</div>}

export default function GenesisV4(){return <main className="genesis-case-study"><GenesisHero/><ProjectSnapshot/>
<section className="genesis-case-section problem-section"><SectionHeader number="01" eyebrow="WHY GENESIS" title="The opportunity was bigger than test creation. It was reducing the manual work around testing." copy="Genesis brings product context, AI assistance, validation, execution and reporting into one experience. The goal was to help technical teams spend less time on repetitive preparation and more time making quality decisions."/><Reveal><BeforeAfter/></Reveal></section>
<section className="genesis-case-section question-section"><div className="big-question"><p className="genesis-section-kicker">THE DESIGN CHALLENGE</p><h2>How do we make AI do more of the work without letting it <em>decide everything?</em></h2><p>That became the core design principle: use AI to accelerate repetitive tasks, but keep consequential choices visible, understandable and reviewable by the people responsible for quality.</p></div></section>
<section className="genesis-case-section workflow-section"><SectionHeader number="02" eyebrow="PRODUCT EXPERIENCE" title="Genesis connects the full testing journey — not just project setup." copy="The setup flow is one layer of the product. Around it are AI-assisted generation, human validation, execution, monitoring and reporting. Each surface exists to move the workflow forward while preserving context."/><Reveal><WorkflowMap/></Reveal></section>
<Chapter number="03" eyebrow="PRODUCT CONTEXT" title="Start by defining what is being tested." copy="A testing system needs product context before it can generate useful work. The first step gives users a clear starting point and establishes the problem before technical configuration begins." visual={<OriginalScreen src="/surya-portfolio/genesis/Project%20Details.png" alt="Original Genesis Project Details screen"/>}/>
<Chapter number="04" eyebrow="PRODUCT CONTEXT" title="Bring the information the AI needs to reason about the product." copy="User stories, API contracts and source code provide different views of the system. Making those inputs explicit helps users understand where generated testing work comes from." visual={<OriginalScreen src="/surya-portfolio/genesis/Input%20Artifacts.png" alt="Original Genesis Input Artifacts screen"/>} reverse/>
<Chapter number="05" eyebrow="TESTING FOUNDATIONS" title="Prepare realistic conditions, not just test cases." copy="Test scenarios depend on data. Genesis gives teams a dedicated place to connect supporting data and decide whether synthetic test data should be used." visual={<OriginalScreen src="/surya-portfolio/genesis/Test%20Data%20Setup.png" alt="Original Genesis Test Data Setup screen"/>}/>
<Chapter number="06" eyebrow="AI CONFIGURATION" title="Make AI configurable and understandable before it acts." copy="The AI is not presented as a single mysterious Generate button. Language, model and capabilities become visible choices so users can understand the configuration behind the generated work." visual={<OriginalScreen src="/surya-portfolio/genesis/AI%20Configuration.png" alt="Original Genesis AI Configuration screen"/>} reverse/>
<Chapter number="07" eyebrow="HUMAN CONTROL" title="Review is the bridge between AI assistance and action." copy="The final checkpoint brings important choices back together. Users can verify the setup before the project is created, making human judgement an intentional part of the workflow." visual={<OriginalScreen src="/surya-portfolio/genesis/Review%20%26%20Validate.png" alt="Original Genesis Review and Validate screen"/>}/>
<section className="genesis-case-section insight-section"><SectionHeader number="08" eyebrow="AFTER SETUP" title="Once the work is automated, teams need visibility into what happened." copy="Genesis continues beyond configuration. Dashboard and reporting surfaces help teams understand testing activity, pass rate, coverage and areas that need attention — turning execution data into actionable insight."/><Reveal><div className="genesis-original-pair"><OriginalScreen src="/surya-portfolio/genesis/Dashboard.png" alt="Original Genesis Dashboard screen"/><OriginalScreen src="/surya-portfolio/genesis/Reports.png" alt="Original Genesis Reports screen"/></div></Reveal></section>
<section className="genesis-case-section states-section"><SectionHeader number="09" eyebrow="DESIGNING FOR TRUST" title="Every state should make the system's behaviour understandable." copy="In an AI-assisted workflow, uncertainty can quickly become friction. Clear empty, input, error and success states help users understand what the product expects, what it is doing and what happens next."/><Reveal><States/></Reveal></section>
<section className="genesis-case-section decisions-section"><SectionHeader number="10" eyebrow="WHAT SHAPED THE DESIGN" title="The product was shaped by four principles, not one feature." copy="The strongest design decisions connected speed, AI transparency, human judgement and the wider testing lifecycle."/><div className="genesis-decision-grid">{decisions.map(([title,text],i)=><Reveal key={title} delay={i*.05}><motion.article whileHover={{y:-6}}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p><ArrowRight size={17}/></motion.article></Reveal>)}</div></section>
<section className="genesis-case-section"><SectionHeader number="11" eyebrow="OUTCOME & LEARNING" title="The value of Genesis is not AI for its own sake. It is less manual work with more informed control." copy="I designed the experience around a balance: automate repetitive parts of testing, make AI behaviour visible, preserve human decision points and give teams a continuous view from setup through reporting. The result is a product story that is broader than any single screen or workflow."/><div className="genesis-before-after"><div className="story-column before"><div className="story-label"><span>WHAT AI HELPS WITH</span><b>01</b></div><h3>Repetitive analysis and generation.</h3><p>Context processing, test generation, code analysis and recommendations can be assisted by AI.</p></div><div className="story-arrow"><ArrowRight size={20}/></div><div className="story-column after"><div className="story-label"><span>WHAT PEOPLE OWN</span><b>02</b></div><h3>Quality decisions and accountability.</h3><p>Users review important configuration and decide when AI-generated work is ready to move forward.</p></div></div></section>
<footer className="genesis-footer"><span>GENESIS / END</span><h2>Designing AI to make testing lighter — without making the human role invisible.</h2><a href="../../">Back to portfolio <ArrowRight size={16}/></a></footer>
</main>}
