import React from 'react';
import { motion } from 'framer-motion';
import { ArrowDown, ArrowRight, Check, ChevronRight, CircleDot, Eye, FileText, Layers3, ShieldCheck, SlidersHorizontal, Sparkles, UploadCloud } from 'lucide-react';
import GenesisHero from './GenesisHero';
import './genesis-case-study.css';

const setup = [
  { n:'01', title:'Project context', short:'Define the problem', text:'Start with what is being tested so the AI has a clear product context.', icon:Layers3 },
  { n:'02', title:'Input artifacts', short:'Bring the right context', text:'Give Genesis requirements, APIs and source-code context it can work from.', icon:UploadCloud },
  { n:'03', title:'Test data setup', short:'Prepare the conditions', text:'Connect the data and environments the generated scenarios depend on.', icon:SlidersHorizontal },
  { n:'04', title:'AI configuration', short:'Make AI explicit', text:'Choose the language, model and capabilities before generation begins.', icon:Sparkles },
  { n:'05', title:'Review & validate', short:'Keep humans in control', text:'Bring the important decisions together before the project is created.', icon:ShieldCheck },
];

const decisions = [
  ['Reduce repetitive effort','Use AI where teams repeatedly analyse, generate and organise testing work.'],
  ['Keep AI understandable','Make important AI inputs, model choices and capabilities visible.'],
  ['Keep humans accountable','Create deliberate review points before consequential work moves forward.'],
  ['Design the whole lifecycle','Connect setup, execution, monitoring and reporting into one product experience.'],
];

function Reveal({children,delay=0,className=''}:{children:React.ReactNode;delay?:number;className?:string}){return <motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.65,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}

function SectionHeader({number,eyebrow,title,copy}:{number:string;eyebrow:string;title:string;copy:string}){return <div className="genesis-section-heading"><div className="genesis-section-number"><span>{number}</span><i/></div><div><p className="genesis-section-kicker">{eyebrow}</p><h2>{title}</h2><p className="genesis-section-copy">{copy}</p></div></div>}

function ProjectSnapshot(){return <section className="genesis-snapshot"><div className="snapshot-intro"><p className="genesis-section-kicker">THE PROJECT, IN ONE MINUTE</p><h2>Genesis is an AI-powered test automation platform designed to reduce repetitive testing work while keeping the people responsible for quality in control.</h2><p>I shaped the end-to-end product experience as the sole designer — from product context and AI configuration to validation, monitoring and reporting.</p></div><div className="snapshot-facts"><div><span>ROLE</span><strong>Product Designer · Sole designer</strong></div><div><span>TEAM</span><strong>PM · Engineers · Stakeholders</strong></div><div><span>USERS</span><strong>QA · Test automation · QE · DevOps</strong></div><div><span>FOCUS</span><strong>AI-assisted testing · SaaS</strong></div></div></section>}

function BeforeAfter(){return <div className="genesis-before-after"><div className="story-column before"><div className="story-label"><span>THE TESTING CHALLENGE</span><b>01</b></div><h3>Testing takes more time than the test run itself.</h3><p>Teams spend effort understanding requirements, preparing data, creating test cases, configuring automation, investigating results and tracking coverage. Genesis was designed to reduce that surrounding manual work.</p><div className="fragment-stack"><span>Requirements</span><span>APIs & code</span><span>Test data</span><span>Test generation</span><span>Execution</span><span>Reporting</span></div></div><div className="story-arrow"><ArrowRight size={20}/></div><div className="story-column after"><div className="story-label"><span>THE PRODUCT OPPORTUNITY</span><b>02</b></div><h3>Let AI handle repetitive work while people retain the important decisions.</h3><p>The experience connects AI assistance with explicit human checkpoints, so speed does not come at the cost of visibility or control.</p><div className="sequence-mini"><span><b>AI</b>Analyze</span><span><b>AI</b>Generate</span><span><b>AI</b>Recommend</span><span><b>HUMAN</b>Review</span><span><b>HUMAN</b>Approve</span></div></div></div>}

function AIModel(){return <div className="test-data-visual"><div className="data-card"><span>AI + HUMAN DECISION MODEL</span><h3>Assistance without a black box.</h3><p>AI accelerates repetitive work. Humans remain visible at the points where quality decisions matter.</p><div className="data-row"><b>AI assists</b><small>Analyse · Generate · Recommend</small></div><div className="toggle-row"><b>Human control</b><small>Review · Modify · Approve</small></div></div><div className="data-orbit"><CircleDot size={18}/></div></div>}

function WorkflowMap(){return <div className="genesis-workflow-map"><div className="workflow-line"/>{setup.map(({n,title,text,icon:Icon})=><motion.article key={n} whileHover={{y:-7}} className="workflow-node"><span className="workflow-number">{n}</span><div className="workflow-icon"><Icon size={18}/></div><h3>{title}</h3><p>{text}</p></motion.article>)}</div>}

function Screen({type}:{type:'project'|'artifacts'|'data'|'ai'|'review'|'reports'}){
 if(type==='project')return <div className="screen-frame project-screen"><div className="screen-chrome"><span/><span/><span/><small>Project Details</small></div><div className="screen-layout"><aside><b>G</b><i/><i/><i/><i/></aside><div className="screen-content"><small>01 / 05 · PROJECT DETAILS</small><h4>Start with the product context.</h4><label>PROJECT NAME<div>Project Genesis</div></label><label>DESCRIPTION<div>AI-powered test automation workspace</div></label><button>Next <ChevronRight size={13}/></button></div></div></div>;
 if(type==='artifacts')return <div className="screen-frame artifacts-screen"><div className="screen-chrome"><span/><span/><span/><small>Input Artifacts</small></div><div className="artifact-content"><small>02 / 05 · INPUT ARTIFACTS</small><h4>Give the AI the context it can reason from.</h4><div className="artifact-grid"><div><FileText size={19}/><b>User Stories</b><span>Requirements & acceptance criteria</span></div><div><CircleDot size={19}/><b>API Contracts</b><span>OpenAPI / Swagger</span></div><div><UploadCloud size={19}/><b>GitHub Repository</b><span>Source code context</span></div></div></div></div>;
 if(type==='data')return <div className="test-data-visual"><div className="data-card"><span>03 / 05 · TEST DATA SETUP</span><h3>Prepare the conditions behind the tests.</h3><p>Make supporting data part of the workflow instead of a separate manual task.</p><div className="data-row"><b>Database connection</b><small>Configured</small></div><div className="toggle-row"><b>Enable synthetic test data</b><i className="toggle-on"/></div></div><div className="data-orbit"><CircleDot size={18}/></div></div>;
 if(type==='ai')return <div className="screen-frame ai-screen"><div className="screen-chrome"><span/><span/><span/><small>AI Configuration</small></div><div className="ai-screen-content"><small>04 / 05 · AI CONFIGURATION</small><h4>Make the intelligence visible.</h4><div className="ai-setting"><span>Programming language</span><b>TypeScript</b><ChevronRight size={14}/></div><div className="ai-setting"><span>LLM model</span><b>GPT model</b><ChevronRight size={14}/></div><div className="ai-capability"><span><Check size={13}/> Test generation</span><span><Check size={13}/> Code analysis</span><span><Eye size={13}/> Bug detection</span></div></div></div>;
 if(type==='review')return <div className="screen-frame review-screen"><div className="screen-chrome"><span/><span/><span/><small>Review & Validate</small></div><div className="review-content"><small>05 / 05 · REVIEW & VALIDATE</small><h4>The human gets the final say.</h4><div className="review-summary"><div><span>Language</span><b>TypeScript</b></div><div><span>LLM model</span><b>GPT model</b></div><div><span>Synthetic data</span><b>Enabled</b></div><div><span>Capabilities</span><b>Configured</b></div></div><button>Create Project <ArrowRight size={13}/></button></div></div>;
 return <div className="screen-frame reports-screen"><div className="screen-chrome"><span/><span/><span/><small>Genesis Dashboard & Reports</small></div><div className="dashboard-content"><small>QUALITY OVERVIEW</small><h4>See what needs attention.</h4><div className="dashboard-kpis"><span><b>12</b>Active projects</span><span><b>47</b>Test cycles</span><span><b>94.2%</b>Pass rate</span><span><b>87.5%</b>Coverage</span></div><div className="dashboard-charts"><div><span>Testing activity & trends</span><svg viewBox="0 0 360 90"><path d="M0 72 C35 60 50 78 86 55 S140 68 168 45 S220 55 250 30 S300 42 360 14"/></svg></div><div className="donut"><i>94%</i></div></div></div></div>;
}

function Chapter({number,eyebrow,title,copy,visual,reverse=false}:{number:string;eyebrow:string;title:string;copy:string;visual:React.ReactNode;reverse?:boolean}){return <section className={`genesis-case-section chapter-section ${reverse?'chapter-reverse':''}`}><div className="chapter-copy"><div className="chapter-number">{number}</div><p className="genesis-section-kicker">{eyebrow}</p><h2>{title}</h2><p>{copy}</p></div><Reveal className="chapter-visual">{visual}</Reveal></section>}

function States(){const states=[['Empty','Nothing to start yet','neutral'],['Input','Context received','active'],['Error','Something needs attention','error'],['Success','Action completed','success']];return <div className="genesis-state-strip">{states.map(([title,value,type])=><motion.div key={title} whileHover={{y:-5}} className={`state-card ${type}`}><small>{title}</small><div>{value}</div><span>{type==='error'?'!':type==='success'?'✓':'•'}</span></motion.div>)}</div>}

export default function GenesisV4(){return <main className="genesis-case-study"><GenesisHero/><ProjectSnapshot/>
<section className="genesis-case-section problem-section"><SectionHeader number="01" eyebrow="WHY GENESIS" title="The opportunity was bigger than test creation. It was reducing the manual work around testing." copy="Genesis brings product context, AI assistance, validation, execution and reporting into one experience. The goal was to help technical teams spend less time on repetitive preparation and more time making quality decisions."/><Reveal><BeforeAfter/></Reveal></section>
<section className="genesis-case-section question-section"><div className="big-question"><p className="genesis-section-kicker">THE DESIGN CHALLENGE</p><h2>How do we make AI do more of the work without letting it <em>decide everything?</em></h2><p>That became the core design principle: use AI to accelerate repetitive tasks, but keep consequential choices visible, understandable and reviewable by the people responsible for quality.</p></div></section>
<section className="genesis-case-section workflow-section"><SectionHeader number="02" eyebrow="PRODUCT EXPERIENCE" title="Genesis connects the full testing journey — not just project setup." copy="The setup flow is one layer of the product. Around it are AI-assisted generation, human validation, execution, monitoring and reporting. Each surface exists to move the workflow forward while preserving context."/><Reveal><WorkflowMap/></Reveal></section>
<Chapter number="03" eyebrow="PRODUCT CONTEXT" title="Start by defining what is being tested." copy="A testing system needs product context before it can generate useful work. The first step gives users a clear starting point and establishes the problem before technical configuration begins." visual={<Screen type="project"/>}/>
<Chapter number="04" eyebrow="PRODUCT CONTEXT" title="Bring the information the AI needs to reason about the product." copy="User stories, API contracts and source code provide different views of the system. Making those inputs explicit helps users understand where generated testing work comes from." visual={<Screen type="artifacts"/>} reverse/>
<Chapter number="05" eyebrow="TESTING FOUNDATIONS" title="Prepare realistic conditions, not just test cases." copy="Test scenarios depend on data. Genesis gives teams a dedicated place to connect supporting data and decide whether synthetic test data should be used." visual={<Screen type="data"/>}/>
<Chapter number="06" eyebrow="AI CONFIGURATION" title="Make AI configurable and understandable before it acts." copy="The AI is not presented as a single mysterious Generate button. Language, model and capabilities become visible choices so users can understand the configuration behind the generated work." visual={<Screen type="ai"/>} reverse/>
<Chapter number="07" eyebrow="HUMAN CONTROL" title="Review is the bridge between AI assistance and action." copy="The final checkpoint brings important choices back together. Users can verify the setup before the project is created, making human judgement an intentional part of the workflow." visual={<Screen type="review"/>}/>
<section className="genesis-case-section insight-section"><SectionHeader number="08" eyebrow="AFTER SETUP" title="Once the work is automated, teams need visibility into what happened." copy="Genesis continues beyond configuration. Dashboard and reporting surfaces help teams understand testing activity, pass rate, coverage and areas that need attention — turning execution data into actionable insight."/><Reveal><Screen type="reports"/></Reveal></section>
<section className="genesis-case-section states-section"><SectionHeader number="09" eyebrow="DESIGNING FOR TRUST" title="Every state should make the system's behaviour understandable." copy="In an AI-assisted workflow, uncertainty can quickly become friction. Clear empty, input, error and success states help users understand what the product expects, what it is doing and what happens next."/><Reveal><States/></Reveal></section>
<section className="genesis-case-section decisions-section"><SectionHeader number="10" eyebrow="WHAT SHAPED THE DESIGN" title="The product was shaped by four principles, not one feature." copy="The strongest design decisions connected speed, AI transparency, human judgement and the wider testing lifecycle."/><div className="genesis-decision-grid">{decisions.map(([title,text],i)=><Reveal key={title} delay={i*.05}><motion.article whileHover={{y:-6}}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p><ArrowRight size={17}/></motion.article></Reveal>)}</div></section>
<section className="genesis-case-section"><SectionHeader number="11" eyebrow="OUTCOME & LEARNING" title="The value of Genesis is not AI for its own sake. It is less manual work with more informed control." copy="I designed the experience around a balance: automate repetitive parts of testing, make AI behaviour visible, preserve human decision points and give teams a continuous view from setup through reporting. The result is a product story that is broader than any single screen or workflow."/><div className="genesis-before-after"><div className="story-column before"><div className="story-label"><span>WHAT AI HELPS WITH</span><b>01</b></div><h3>Repetitive analysis and generation.</h3><p>Context processing, test generation, code analysis and recommendations can be assisted by AI.</p></div><div className="story-arrow"><ArrowRight size={20}/></div><div className="story-column after"><div className="story-label"><span>WHAT PEOPLE OWN</span><b>02</b></div><h3>Quality decisions and accountability.</h3><p>Users review important configuration and decide when AI-generated work is ready to move forward.</p></div></div></section>
<footer className="genesis-footer"><span>GENESIS / END</span><h2>Designing AI to make testing lighter — without making the human role invisible.</h2><a href="../../">Back to portfolio <ArrowRight size={16}/></a></footer>
</main>}
